spring:
  cloud:
    gateway:
      default-filters: []
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "${CORS_ALLOWED_ORIGINS}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        connect-timeout: 5000
        response-timeout: 5s
      discovery:
        locator:
          enabled: false
      routes:
        - id: usuarios
          uri: ${USUARIOS_SERVICE_URL}
          predicates:
            - Path=/usuarios/**

        - id: videojuegos
          uri: ${VIDEOJUEGOS_SERVICE_URL}
          predicates:
            - Path=/videojuegos/**

        - id: pedidos
          uri: ${PEDIDOS_SERVICE_URL}
          predicates:
            - Path=/pedidos/**

        - id: detalles
          uri: ${PEDIDOS_SERVICE_URL}
          predicates:
            - Path=/detalles/**

        - id: facturas
          uri: ${FACTURAS_SERVICE_URL}
          predicates:
            - Path=/facturas/**

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG